monitoring:
  image:
    repository: containers.renci.org/appstore-sockets/monitoring
    pullPolicy: IfNotPresent
    tag: ""
  
  resources: {}

image:
  repository: containers.renci.org/appstore-sockets/server
  pullPolicy: IfNotPresent
  tag: ""

nameOverride: ""
fullnameOverride: ""

requirePublishSecret: true

podAnnotations: {}

serviceAccount:
  create: true
  annotations: {}
  name:

securityContext:
  runAsUser: 0
  runAsGroup: 0
  fsGroup: 0

serviceName: appstore-sockets-service
service:
  type: ClusterIP
  port: 80
  name: http

resources: {}

ambassador:
   flag: true

global:
  ambassador_id:

nodeSelector: {}

tolerations: []

affinity: {}