monitoring:
  image:
    repository: frostyfan109/ws-monitoring
    pullPolicy: IfNotPresent
    tag: v1.1.0
  
  resources: {}


image:
  repository: frostyfan109/ws-test
  pullPolicy: IfNotPresent
  tag: v1.1.0

nameOverride: ""
fullnameOverride: ""

requirePublishSecret: true

podAnnotations: {}

serviceAccount:
  create: true
  annotations: {}
  name:

securityContext:
  runAsUser: 0
  runAsGroup: 0
  fsGroup: 0

serviceName: appstore-ws-service
service:
  type: ClusterIP
  port: 80
  name: http

resources: {}

ambassador:
   flag: true

global:
  ambassador_id:

nodeSelector: {}

tolerations: []

affinity: {}