apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "appstore-sockets.fullname" . }}
  labels:
    {{- include "appstore-sockets.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "appstore-sockets.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "appstore-sockets.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "appstore-sockets.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default (printf "v%s" .Chart.AppVersion) }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5555
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: NODE_ENV
              value: production
            - name: REQUIRE_PUBLISH_SECRET
              valueFrom:
                configMapKeyRef:
                  key: REQUIRE_PUBLISH_SECRET
                  name: {{ include "appstore-sockets.fullname" . }}-env
            - name: PUBLISHER_SECRET
              valueFrom:
                secretKeyRef:
                  key: PUBLISHER_SECRET
                  name: {{ include "appstore-sockets.fullname" . }}
            - name: APPSTORE_HOST
              valueFrom:
                configMapKeyRef:
                  key: APPSTORE_HOST
                  name: {{ include "appstore-sockets.fullname" . }}-env
        - name: {{ .Chart.Name }}-monitoring
          image: "{{ .Values.monitoring.image.repository }}:{{ .Values.monitoring.image.tag | default (printf "v%s" .Chart.AppVersion) }}"
          imagePullPolicy: {{ .Values.monitoring.image.pullPolicy }}
          resources:
            {{- toYaml .Values.monitoring.resources | nindent 12 }}
          env:
            - name: WS_HOST
              value: {{ .Values.serviceName }}
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: PUBLISHER_SECRET
              valueFrom:
                secretKeyRef:
                  key: PUBLISHER_SECRET
                  name: {{ include "appstore-sockets.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
