apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.serviceName }}-webhook-policy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: appstore-ws
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: appstore