{{- if .Values.serviceAccount.create -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "appstore-sockets.fullname" . }}-role
rules:
- apiGroups:
  - ""
  resources:
    - pods
    - events
  verbs:
    - get
    - list
    - watch
{{- end }}