apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  labels:
    {{- include "appstore-sockets.labels" . | nindent 4 }}
  {{- if .Values.ambassador.flag }}
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: appstore-sockets-sock-mapping
      use_websocket: true
      prefix: /ws
      rewrite: /ws
      service: {{ .Values.serviceName }}:5555
      {{ if .Values.global.ambassador_id }}
      ambassador_id: {{ .Values.global.ambassador_id }}
      {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.name }}
      protocol: TCP
      port: 5555
      targetPort: 5555
  selector:
    {{- include "appstore-sockets.selectorLabels" . | nindent 4 }}