# This chart catches changes pushed to main branch of this repo
# Then triggers the parent repo that holds all Helx Charts, "Helm-Charts"
# To package and release the new updates.

name: Trigger-Helm-Charts
on:
  push:
    branches:
      - main 
      - master
    paths-ignore:
      - .github/workflows/*
      - .github/*
jobs:
  trigger-helm-charts:
    runs-on: ubuntu-latest
    steps:

    - name: Trigger Helm-Charts Workflow
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: | 
        gh --repo https://github.com/helxplatform/helm-charts \
        workflow run package-index.yml \
        -f appRepo=${{ github.repository }} \
        -f actor=${{ github.actor }} \
        --ref develop
